# Generated by Django 4.2.7 on 2023-12-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Identificacion')),
                ('name', models.CharField(max_length=80, verbose_name='Nombres')),
                ('last', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('phone', models.CharField(max_length=100, verbose_name='Telefono')),
                ('image', models.ImageField(upload_to='clients', verbose_name='Capturar')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Localidd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Codigo Postal')),
                ('name', models.CharField(max_length=80, verbose_name='Localidad')),
                ('municipalit', models.CharField(max_length=80, verbose_name='Municipio')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Municip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Codigo Postal')),
                ('name', models.CharField(max_length=80, verbose_name='Municipio')),
                ('estado', models.CharField(choices=[('1', 'Aguascalientes'), ('2', 'Baja California'), ('3', 'Baja California Sur'), ('4', 'Campeche'), ('5', 'Chiapas'), ('6', 'Chihuahua'), ('7', 'Ciudad de México'), ('8', 'Coahuila'), ('9', 'Colima'), ('10', 'Durango'), ('11', 'Estado de México'), ('13', 'Guanajuato'), ('14', 'Guerrero'), ('15', 'Hidalgo'), ('16', 'Jalisco'), ('17', 'Michoacán'), ('18', 'Morelos'), ('19', 'Nayarit'), ('20', 'Nuevo León'), ('21', 'Oaxaca'), ('22', 'Puebla'), ('23', 'Querétaro'), ('24', 'Quintana Roo'), ('25', 'San Luis Potosí'), ('26', 'Sinaloa'), ('27', 'Sonora'), ('28', 'Tabasco'), ('29', 'Tamaulipas'), ('30', 'Tlaxcala'), ('31', 'Veracruz'), ('32', 'Yucatán'), ('33', 'Zacatecas')], default='1', max_length=50)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Produc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='codigo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('expiration', models.CharField(max_length=40, verbose_name='Caducidad')),
                ('categoria', models.CharField(max_length=200, verbose_name='Categoria')),
                ('proveedor', models.CharField(max_length=50, verbose_name='Proveedor')),
                ('image', models.ImageField(upload_to='Products', verbose_name='Capturar')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Identificacion')),
                ('name', models.CharField(max_length=80, verbose_name='Nombres')),
                ('last', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('company', models.CharField(max_length=150, verbose_name='Empresa')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefono')),
                ('mail', models.CharField(max_length=100, verbose_name='Correo Electronico')),
                ('image', models.ImageField(upload_to='proveeds', verbose_name='Capturar')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Provedores',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('amount', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('expiration', models.CharField(max_length=40, verbose_name='Caducidad')),
                ('image', models.ImageField(upload_to='salidaProducts', verbose_name='Capturar')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('catego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.categ')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.cliente')),
                ('cod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.produc')),
                ('localid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.localidd')),
                ('municip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.municip')),
            ],
            options={
                'verbose_name': 'Salida De Producto',
                'verbose_name_plural': 'Salidas De Productos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('amount', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('expiration', models.CharField(max_length=40, verbose_name='Caducidad')),
                ('image', models.ImageField(upload_to='salidaProducts', verbose_name='Capturar')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('catego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.categ')),
                ('cod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.produc')),
                ('porved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.proveedor')),
            ],
            options={
                'verbose_name': 'Entrada De Producto',
                'verbose_name_plural': 'Entradas De Productos',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='localid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.localidd'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.municip'),
        ),
    ]
