# Generated by Django 4.2.7 on 2024-01-04 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stored', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produc',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='produc',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.categ'),
        ),
    ]
