# Generated by Django 4.2.7 on 2024-01-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stored', '0002_remove_produc_proveedor_alter_produc_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='localid',
            new_name='localidad',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='municip',
            new_name='municipio',
        ),
        migrations.RenameField(
            model_name='entradas',
            old_name='catego',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='entradas',
            old_name='cod',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='entradas',
            old_name='porved',
            new_name='porveedor',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='catego',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='client',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='cod',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='localid',
            new_name='localidad',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='municip',
            new_name='municipio',
        ),
    ]
