# Generated by Django 4.2.7 on 2023-11-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Codigo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('amount', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('customer', models.CharField(max_length=200, verbose_name='Cliente')),
                ('location', models.CharField(max_length=150, verbose_name='Localidad')),
                ('image', models.ImageField(upload_to='projects', verbose_name='Capturar')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
                'ordering': ['-created'],
            },
        ),
    ]
