# Generated by Django 4.2.7 on 2023-11-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='Codigo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('category', models.CharField(max_length=200, verbose_name='Categoria')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('amount', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('extent', models.CharField(max_length=200, verbose_name='Tipo de medidas Kg. o L. ')),
                ('image', models.ImageField(upload_to='Catalags', verbose_name='Imagen')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'catalago',
                'verbose_name_plural': 'catalagos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('last', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('position', models.CharField(max_length=200, verbose_name='Puesto')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefono')),
                ('image', models.ImageField(upload_to='Contacts', verbose_name='Imagen')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Codigo De Producto')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('discount', models.PositiveIntegerField(verbose_name='Descuento')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('startt', models.PositiveIntegerField(verbose_name='Dia de inicio')),
                ('startMonth', models.PositiveIntegerField(verbose_name='Mes de inicio')),
                ('ending', models.PositiveIntegerField(verbose_name='Dia de finalizacion')),
                ('monthOfCompletion', models.PositiveIntegerField(verbose_name='Mes de finalizacion')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('amount', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('image', models.ImageField(upload_to='Descuents', verbose_name='Imagen')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'descuento',
                'verbose_name_plural': 'descuentos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='Numero de Tienda')),
                ('name', models.CharField(max_length=200, verbose_name='Localidad')),
                ('municipality', models.CharField(max_length=200, verbose_name='Municipio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('schedule', models.CharField(max_length=200, verbose_name='Horario de atención')),
                ('days', models.CharField(max_length=200, verbose_name='Dias de atención')),
                ('image', models.ImageField(upload_to='Sucursals', verbose_name='Imagen')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ['-created'],
            },
        ),
    ]
