# Generated by Django 4.2.7 on 2024-01-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stored', '0003_rename_localid_cliente_localidad_and_more'),
        ('front', '0002_catalago_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalago',
            name='category',
        ),
        migrations.RemoveField(
            model_name='catalago',
            name='code',
        ),
        migrations.RemoveField(
            model_name='discounts',
            name='code',
        ),
        migrations.RemoveField(
            model_name='sucursales',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='sucursales',
            name='name',
        ),
        migrations.AddField(
            model_name='catalago',
            name='Codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.produc'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='Codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.produc'),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.localidd'),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stored.municip'),
        ),
    ]
